# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Recommenders',
                'verbose_name': 'Recommender',
            },
        ),
        migrations.CreateModel(
            name='RecommenderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_id_judge', models.IntegerField()),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Recommender')),
            ],
            options={
                'verbose_name_plural': 'Recommender Categories',
                'verbose_name': 'Recommender Category',
            },
        ),
        migrations.CreateModel(
            name='RecommenderThetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Problem')),
                ('recommeder_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.RecommenderCategory')),
            ],
        ),
    ]
